In [2]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

## Creating numpy arrays

### Directly

In [3]:
a = np.array(
    [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0], 
     [7.0, 8.0, 9.0]]
)

print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### From a list

In [4]:
a = [[1.0, 2.0, 3.0], 
     [4.0, 5.0, 6.0], 
     [7.0, 8.0, 9.0]]

print(a)
print()

a = np.array(a)

print(a)

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### From a list comprehension

In [ ]:
a = [i**2 for i in range(10)]

print(a)
print()
print(np.array(a))

### Ready-made functions in numpy

In [ ]:
# All zeros
a = np.zeros((3, 4))
print("All zeros")
print(a)
print()

# All a chosen value
a = np.full((3, 4), 7.0)
print("All chosen value (variant 1)")
print(a)
print()

# or

a = np.zeros((3, 4))
a[:] = 7.0
print("All chosen value (variant 2)")
print(a)
print()

# Random integers

a = np.random.randint(low=0, high=10, size=(3, 2))
print("Random integers")
print(a)
print()

# Random values from the normal distribution (Gaussian)

print("Random values from the normal distribution")
a = np.random.normal(loc=0, scale=10, size=(3, 2))
print(a)

## Slicing numpy arrays

### Slicing in 1D

To obtain only specific values from a numpy array one can use so called slicing. It has the form

**arr[low:high:step]**

where low is the lowest index to be retrieved, high is the lowest index not to be retrieved and step indicates that every step element will be taken.

In [ ]:
a = [i**2 for i in range(10)]

print("Original: ", a)
print("First 5 elements:", a[:5])
print("Elements from index 3 to index 5:", a[3:6])
print("Last 3 elements (negative indexing):", a[-3:])
print("Printed in reverse order:", a[::-1])
print("Every second element:", a[::2])

### Slicing in 2D

In two dimensions it works similarly, just the slicing is separate for every dimension.

In [ ]:
a = np.array([i for i in range(25)]).reshape(5, 5)

print("Original: ")
print(a)
print()
print("First 2 elements of the first 3 row:")
print(a[:3, :2])
print()
print("Middle 3 elements from the middle 3 rows:")
print(a[1:4, 1:4])
print()
print("Bottom-right 3 by 3 submatrix (negative indexing):")
print(a[-3:, -3:])
print()
print("Reversed columns:")
print(a[:, ::-1])
print()

### Setting numpy array field values

In [ ]:
a = np.array([i for i in range(25)]).reshape(5, 5)

print("Original: ")
print(a)
print()

a[1:4, 1:4] = 5.0

print("Middle values changed to 5")
print(a)
print()

b = np.array([i**2 - i for i in range(9)]).reshape(3, 3)

print("Second matrix")
print(b)
print()

a[1:4, 1:4] = b

print("Second matrix substituted into the middle of the first matrix")
print(a)

## Operations on numpy arrays

It is important to remember that arithmetic operations on numpy arrays are always element-wise.

In [ ]:
a = np.array([i**2 for i in range(9)]).reshape((3, 3))
print(a)
print()

b = np.array([i**0.5 for i in range(9)]).reshape((3, 3))
print(b)
print()

### Element-wise sum

In [ ]:
print(a + b)

### Element-wise multiplication

In [ ]:
print(a * b)

### Matrix multiplication

In [ ]:
print(np.matmul(a, b))
print()

# Multiplication by the identity matrix (to check it works as expected)
id_matrix = [[1.0, 0.0, 0.0], 
             [0.0, 1.0, 0.0], 
             [0.0, 0.0, 1.0]]

print(np.matmul(id_matrix, a))

### Calculating the mean

In [ ]:
a = np.random.randint(low=0, high=10, size=(5))

print(a)
print()

print("Mean: ", np.sum(a) / len(a))

### Calculating the mean of every row

In [ ]:
a = np.random.randint(low=0, high=10, size=(5, 3))

print(a)
print()

print("Mean:", np.sum(a, axis=1) / a.shape[1])

print("Mean in the original matrix form:")
print((np.sum(a, axis=1) / a.shape[1]).reshape(-1, 1))  # -1 calculates the right size to use all elements

### More complex operations

In [ ]:
a = [1.0, 2.0, 3.0]

print("Vector to power 2 (element-wise)")
print(np.power(a, 2))
print()
print("Euler number to the power a (element-wise)")
print(np.exp(a))
print()
print("An even more complex expression")
print((np.power(a, 2) + np.exp(a)) / np.sum(a))

## Numpy tasks

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [8]:
b = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25])
a = np.array([1/(1 + np.exp(-i)) for i in b])
print(a[-5:])

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [10]:
x = np.array([3,1,4,2,6,1,4,8])
y = np.array([5,2,3,12,2,4,17,11])
a = np.sum(x*y)
print(a)
b = np.dot(x,y)
print(b)
c = np.matmul(x,y)
print(c)

225
225
225


**Task 3.** Calculate the following expression<br/>
$$\frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, -2.1, -3.3, 0.2]$<br/>
$\theta = [7.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, 1.65]$<br/>
and print the result. Use only vector operations.

In [22]:
𝑥=np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,-2.1,-3.3,0.2, 1])
t = np.array([7.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,1.65])
xt = -x*t
epower = np.sum(np.array(xt))
result = 1/(1 + np.exp(epower))
print(result)

1.3644840814871147e-15


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [3]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Peek into the datasets

In [24]:
steam_df.head(10)

user-id                  game-title behavior-name  value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1  151603712  The Elder Scrolls V Skyrim          play  273.0     0
2  151603712                   Fallout 4      purchase    1.0     0
3  151603712                   Fallout 4          play   87.0     0
4  151603712                       Spore      purchase    1.0     0
5  151603712                       Spore          play   14.9     0
6  151603712           Fallout New Vegas      purchase    1.0     0
7  151603712           Fallout New Vegas          play   12.1     0
8  151603712               Left 4 Dead 2      purchase    1.0     0
9  151603712               Left 4 Dead 2          play    8.9     0

In [25]:
ml_ratings_df.head(10)

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [4]:
ml_movies_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

## Merge both MovieLens DataFrames into one

In [27]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Choosing a row, a column or several columns

In [28]:
display(HTML(steam_df.head(10).to_html()))

# Choosing rows by index
chosen_df = steam_df[3:6]

print("Choosing rows by index")
display(HTML(chosen_df.head(10).to_html()))

# Choosing rows by position
chosen_df = steam_df.iloc[3:6]

print("Choosing rows by position")
display(HTML(chosen_df.head(10).to_html()))

Choosing rows by index


Choosing rows by position


In [ ]:
# Choosing a column
chosen_df = steam_df["game-title"]

print(chosen_df.head(10))

In [ ]:
# Choosing several columns
chosen_df = steam_df[['user-id', 'game-title']]

display(HTML(chosen_df.head(10).to_html()))

### Splitting the dataset into training and test set

In [29]:
shuffle = np.array(list(range(len(steam_df))))

# alternatively

shuffle = np.arange(len(steam_df))

np.random.shuffle(shuffle)
shuffle = list(shuffle)
print("Shuffled range of indices")
print(shuffle[:20])
print()

train_test_split = 0.8
split_index = int(len(steam_df) * train_test_split)

training_set = steam_df.iloc[shuffle[:split_index]]
test_set = steam_df.iloc[shuffle[split_index:]]

display(HTML(training_set.head(10).to_html()))

display(HTML(test_set.head(10).to_html()))

Shuffled range of indices
[157311, 123582, 61897, 141814, 79799, 67226, 40624, 113174, 55163, 122777, 86265, 59561, 6537, 48352, 43983, 31875, 101324, 46158, 12922, 16565]



## Filtering

### Filtering columns

In [ ]:
chosen_df = steam_df.loc[:, ['user-id', 'game-title']]

display(HTML(chosen_df.head(10).to_html()))

### Filtering rows

In [ ]:
condition = steam_df['game-title'] == 'Fallout 4'

print(condition.head(10))

chosen_df = steam_df.loc[condition]

display(HTML(chosen_df.head(10).to_html()))

### Filtering rows and columns at once

In [ ]:
condition = (steam_df['game-title'] == 'Fallout 4') & (steam_df['behavior-name'] == 'play')

chosen_df = steam_df.loc[condition, ['user-id', 'game-title', 'value']]

display(HTML(chosen_df.head(10).to_html()))

## Simple operations on columns

### Multiply a column by 2

In [ ]:
steam_df_copy = steam_df.copy()

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value'] = steam_df_copy['value'] * 2

display(HTML(steam_df_copy.head(10).to_html()))

### Choose the first n letters of a string

In [ ]:
ml_movies_df_copy = ml_movies_df.copy()

display(HTML(ml_movies_df_copy.head(10).to_html()))

ml_movies_df_copy.loc[:, 'title'] = ml_movies_df_copy['title'].str[:6]

display(HTML(ml_movies_df_copy.head(10).to_html()))

### Take the mean of a column

In [ ]:
# Option 1
print(steam_df['value'].mean())

# Option 2
print(np.mean(steam_df['value']))

### Simple operation on filtered data

In [38]:
steam_df_copy = steam_df.loc[((steam_df['game-title'] == 'Fallout 4') | (steam_df['game-title'] == 'The Elder Scrolls V Skyrim')) 
                             & (steam_df['behavior-name'] == 'play')].copy()

display(HTML(steam_df_copy.head(10).to_html()))

condition = (steam_df_copy['game-title'] == 'Fallout 4') & (steam_df_copy['behavior-name'] == 'play')

steam_df_copy.loc[condition, 'value'] = steam_df_copy.loc[condition, 'value'] * 2

display(HTML(steam_df_copy.head(10).to_html()))

## Advanced operations on columns

In [ ]:
def reduce_outliers(x):
    return min(np.log(1 + x), 4)

steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value'] = steam_df_copy['value'].apply(reduce_outliers)

display(HTML(steam_df_copy.head(10).to_html()))

### The same apply operation can be achieved with the use of a lambda function

In [ ]:
steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value'] = steam_df_copy['value'].apply(lambda x: min(np.log(1 + x), 4))

display(HTML(steam_df_copy.head(10).to_html()))

### Apply on two columns at once

In [52]:
steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play'].copy()

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value_2'] = steam_df_copy['value'].apply(lambda x: min(np.log(1 + x), 4))

display(HTML(steam_df_copy.head(10).to_html()))

steam_df_copy.loc[:, 'value'] = steam_df_copy[['value', 'value_2']].apply(lambda x: x[0] * x[1], axis=1)

display(HTML(steam_df_copy.head(10).to_html()))

In [ ]:
ml_movies_df_copy = ml_movies_df.copy()

display(HTML(ml_movies_df_copy.head(10).to_html()))

ml_movies_df_copy.loc[:, 'title|genres'] = ml_movies_df_copy[['title', 'genres']].apply(lambda x: x[0] + "|" + x[1], axis=1)

display(HTML(ml_movies_df_copy.head(10).to_html()))

## Grouping and aggregating

### Find the most popular games (in terms of purchases)

In [40]:
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['game-title', 'value']]
steam_grouped = steam_grouped.groupby('game-title').sum()
steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()

display(HTML(steam_grouped.head(10).to_html()))

## Iterating over a DataFrame (if possible, use column operations instead)

In [31]:
i = 0
for idx, row in steam_df.iterrows():
    print("[{}, {}, {}]".format(row['user-id'], row['game-title'], row['behavior-name']))
    i += 1
    if i == 10:
        break

[151603712, The Elder Scrolls V Skyrim, purchase]
[151603712, The Elder Scrolls V Skyrim, play]
[151603712, Fallout 4, purchase]
[151603712, Fallout 4, play]
[151603712, Spore, purchase]
[151603712, Spore, play]
[151603712, Fallout New Vegas, purchase]
[151603712, Fallout New Vegas, play]
[151603712, Left 4 Dead 2, purchase]
[151603712, Left 4 Dead 2, play]


## Pandas tasks - Steam dataset

**Task 4.** How many people made a purchase in the Steam dataset? Remember that a person could by many games, but you need to count every person once.

In [53]:
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['user-id', 'game-title']]
steam_grouped = steam_grouped.groupby('user-id').sum()
steam_grouped = steam_grouped.sort_values(by='user-id', ascending=False).reset_index()
result = len(steam_grouped)
print(result)
#display(HTML(steam_grouped.tail(3).to_html()))

12393


**Task 5.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [46]:
condition = (steam_df['game-title'] == 'The Elder Scrolls V Skyrim') & (steam_df['behavior-name'] == 'purchase')
steam_grouped = steam_df.loc[condition, ['user-id', 'game-title']]
steam_grouped = steam_grouped.groupby('user-id').sum()
steam_grouped = steam_grouped.sort_values(by='user-id', ascending=False).reset_index()
result = len(steam_grouped)
print(result)

717


**Task 6.** How many purchases people made on average?

In [90]:
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['user-id', 'game-title']]
steam_grouped.loc[:, 'game-title'] = steam_grouped[['game-title']].apply(lambda x: x + "nast-", axis=0)
steam_grouped = steam_grouped.groupby('user-id').sum()
steam_grouped = steam_grouped.sort_values(by='game-title', ascending=False).reset_index()

i = 0
arr = list()
for idx, row in steam_grouped.iterrows():
    arr.append(len(str(row['game-title']).split("nast-")) - 1)
    i += 1

result = np.mean(np.array(arr))
print(result)
#display(HTML(steam_grouped.head(10).to_html()))

10.45033486645687


**Task 7.** Who bought the most games?

In [96]:
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['user-id', 'game-title']]
steam_grouped.loc[:, 'game-title'] = steam_grouped[['game-title']].apply(lambda x: x + "nast-", axis=0)
steam_grouped = steam_grouped.groupby('user-id').sum()
steam_grouped = steam_grouped.sort_values(by='game-title', ascending=False).reset_index()

i = 0
arr = list()
for idx, row in steam_grouped.iterrows():
    arr.append(len(str(row['game-title']).split("nast-")) - 1)
    i += 1

ind = arr.index(max(arr))
print(arr[ind])
i = 0
for idx, row in steam_grouped.iterrows():
    if i == ind:
        print("[{}, {}]".format(row['user-id'], row['game-title']))
    i += 1


1075
[62990992, Counter-Strike Global Offensivenast-Sid Meier's Civilization Vnast-Total War SHOGUN 2nast-Total War ROME II - Emperor Editionnast-Dungeon Defendersnast-Age of Empires Onlinenast-XCOM Enemy Unknownnast-Empire Total Warnast-Might & Magic Heroes VInast-Assassin's Creed IV Black Flagnast-Alien Swarmnast-Assassin's Creed IInast-Assassin's Creed Brotherhoodnast-Terra Incognita ~ Chapter One The Descendantnast-Warlock - Master of the Arcanenast-Phantom Breaker Battle Groundsnast-Soul Gamblernast-Supreme Commandernast-The Incredible Adventures of Van Helsing IInast-Titan Quest Immortal Thronenast-Orcs Must Die! 2nast-Assassin's Creed Revelationsnast-Relic Hunters Zeronast-Tom Clancy's Ghost Recon Advanced Warfighternast-Warhammer 40,000 Dawn of War II - Chaos Risingnast-Napoleon Total Warnast-Warhammer 40,000 Dawn of War II  Retributionnast-Uncrowdednast-Alan Wakenast-Ancient Spacenast-R.U.S.Enast-Sometimes Success Requires Sacrificenast-Dead Islandnast-Terrarianast-Why So Evil

**Task 8.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [98]:
condition = (steam_df['game-title'] == 'The Elder Scrolls V Skyrim') & (steam_df['behavior-name'] == 'play')
steam_grouped = steam_df.loc[condition, ['user-id', 'value']]
steam_grouped = steam_grouped.groupby('user-id').sum()
steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()

print(steam_grouped['value'].mean())

display(HTML(steam_grouped.head(10).to_html()))

104.71093057607091


**Task 9.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [44]:
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'play', ['game-title', 'value']]
steam_grouped = steam_grouped.groupby('game-title').sum()
steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()

display(HTML(steam_grouped.head(10).to_html()))

**Task 10.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [103]:
means = list()
condition = (steam_df['behavior-name'] == 'play')
steam_grouped = steam_df.loc[condition, ['game-title']]
games = np.array(steam_grouped)

for title in games:
    condition = (steam_df['game-title'] == title[0]) & (steam_df['behavior-name'] == 'play')
    steam_grouped = steam_df.loc[condition, ['user-id', 'value']]
    steam_grouped = steam_grouped.groupby('user-id').sum()
    steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()
    means.append((title, steam_grouped['value'].mean()))

means.sort(key= lambda x:x[1])
print(means)
#display(HTML(steam_grouped.head(10).to_html()))

KeyboardInterrupt: 

**Task 11\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [ ]:
# Write your code here

**Task 12.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [111]:
steam_df_copy = steam_df.loc[steam_df['behavior-name'] == 'play', ['user-id','game-title', 'value']]
steam_df_copy.loc[:, 'value'] = steam_df_copy[['value']].apply(lambda x: 1/(1 + np.exp(-x/100)), axis=0)
display(HTML(steam_df_copy.head(10).to_html()))

## Pandas tasks - MovieLens dataset

**Task 13\*.** Calculate popularity (by the number of users who watched a movie) of all genres.

In [119]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.tail(10)
ml = ml_df.groupby('genres').count()
ml = ml.sort_values(by='userId', ascending=False).reset_index()
ml.head(10)

genres  userId  movieId  rating  timestamp  title
0                     Comedy    7196     7196    7196       7196   7196
1                      Drama    6291     6291    6291       6291   6291
2             Comedy|Romance    3967     3967    3967       3967   3967
3       Comedy|Drama|Romance    3000     3000    3000       3000   3000
4               Comedy|Drama    2851     2851    2851       2851   2851
5              Drama|Romance    2838     2838    2838       2838   2838
6    Action|Adventure|Sci-Fi    2361     2361    2361       2361   2361
7                Crime|Drama    2315     2315    2315       2315   2315
8      Action|Crime|Thriller    1554     1554    1554       1554   1554
9  Action|Adventure|Thriller    1455     1455    1455       1455   1455

**Task 14\*.** Calculate average rating for all genres.

In [41]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
#ml_df = ml_df[ml_df['genres'] == 'Animation']
ml = ml_df.groupby('genres')
ml = ml['rating'].mean().sort_values(ascending = False)
ml.head(50)

genres
Fantasy|Mystery|Western                                   5.000000
Animation|Children|Mystery                                5.000000
Comedy|Horror|Mystery                                     5.000000
Animation|Drama|Fantasy|Mystery                           5.000000
Drama|Horror|Romance                                      5.000000
Comedy|Drama|Fantasy|Mystery|Romance                      5.000000
Action|Horror|Mystery|Sci-Fi                              5.000000
Adventure|Comedy|Fantasy|Musical                          5.000000
Animation|Drama|Sci-Fi|IMAX                               5.000000
Action|Crime|Drama|Sci-Fi                                 5.000000
Drama|Fantasy|Musical|Mystery|Sci-Fi                      5.000000
Comedy|Crime|Drama|Horror                                 5.000000
Action|Comedy|Drama|Romance                               5.000000
Animation|Crime|Drama                                     5.000000
Comedy|Crime|Fantasy                                   

**Task 15.** Calculate each movie rating bias (deviation from the mean of all movies average ratings). Print first 10 in the form: title, average rating, bias.

In [19]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
#ml_df = ml_df[ml_df['title'] == 'Shrek (2001)']
ml = ml_df.groupby('genres')
ml = ml['rating'].mean().sort_values(ascending = False)

mb = pd.merge(ml, ml_df, on='genres')
mb = mb.rename(columns = {'rating_x': 'avg_rating', 'rating_y': 'rating'})
#mb.loc[:, 'bias'] = mb[['avg_rating','rating']].apply(lambda x: np.std([x[0],x[1]]), axis=1)
#mb = mb.groupby('title')

mb = mb.loc[mb['title'] == 'Shrek (2001)', ['title', 'avg_rating', 'rating']]
mb = mb['rating']
res = np.std(mb)
print(res)

0.919629269368687


**Task 16.** Calculate each movie rating bias (deviation from the mean of all users average ratings). Print first 10 in the form: user_id, average rating, bias.

In [161]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
#ml_df = ml_df[ml_df['genres'] == 'Animation']
ml = ml_df.groupby('genres')
ml = ml['rating'].mean().sort_values(ascending = False)

mb = pd.merge(ml, ml_df, on='genres')
mb = mb.rename(columns = {'rating_x': 'avg_rating', 'rating_y': 'rating'})
mb.loc[:, 'bias'] = mb[['avg_rating','rating']].apply(lambda x: np.std([x[0],x[1]]), axis=1)
mb.head(10)

genres  avg_rating  userId  movieId  rating  \
0               Fantasy|Mystery|Western         5.0     377    42556     5.0   
1            Animation|Children|Mystery         5.0      89   118894     5.0   
2                 Comedy|Horror|Mystery         5.0      89   142444     5.0   
3       Animation|Drama|Fantasy|Mystery         5.0     371   112512     5.0   
4                  Drama|Horror|Romance         5.0     610   107771     5.0   
5  Comedy|Drama|Fantasy|Mystery|Romance         5.0     105   120138     5.0   
6          Action|Horror|Mystery|Sci-Fi         5.0       3     5746     5.0   
7      Adventure|Comedy|Fantasy|Musical         5.0     357     8580     5.0   
8           Animation|Drama|Sci-Fi|IMAX         5.0     477     4454     5.0   
9             Action|Crime|Drama|Sci-Fi         5.0     610   138632     5.0   

    timestamp                               title  bias  
0  1340342545           7 Faces of Dr. Lao (1964)   0.0  
1  1520409061  Scooby-Doo! Abracadabra-Doo (2010)   0.0  
2  1520409484                   The Editor (2015)   0.0  
3  1407692450         Colourful (Karafuru) (2010)   0.0  
4  1479544448       Only Lovers Left Alive (2013)   0.0  
5  1526207544                           PK (2014)   0.0  
6  1306463708     Galaxy of Terror (Quest) (1981)   0.0  
7  1348610734               Into the Woods (1991)   0.0  
8  1245030211                         More (1998)   0.0  
9  1479545420                  Tokyo Tribe (2014)   0.0

**Task 17.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns (use HTML Display for that). You can iterate over the DataFrame in this task.

In [169]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
shuffle = np.array(list(range(len(ml_df))))

split_index = int(len(ml_df) * train_test_split)
train_test_split = 0.8

training_set = ml_df.iloc[shuffle[:split_index]]
test_set = ml_df.iloc[shuffle[split_index:]]

display(HTML(training_set.head(10).to_html()))

## Pandas + numpy tasks

**Task 18.** Create the entire interaction matrix for the MovieLens dataset.

In [35]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml1 = ml_df[ml_df['userId'] == 1]
ml4 = ml_df[ml_df['userId'] == 4]

ml = pd.merge(ml1,ml4,on='movieId')

print(len(ml))

45


**Task 19.** Calculate the matrix of size (n_users, n_users) where at position (i, j) is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml1 = ml_df[ml_df['userId'] == 1]
ml4 = ml_df[ml_df['userId'] == 4]

ml = pd.merge(ml1,ml4,on='movieId')

print(len(ml))

**Task 20.** Calculate the matrix of size (n_items, n_items) where at position (i, j) is the number of users who watched both movie i and movie j. Print the submatrix of first 10 rows and 10 columns.

In [36]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml2 = ml_df[ml_df['movieId'] == 2]
ml3 = ml_df[ml_df['movieId'] == 3]

ml = pd.merge(ml2,ml3,on='userId')

print(len(ml))

26
